////////////////////////////////////////////////////////////////////////////////
//
// This file is part of Strata.
// 
// Strata is free software: you can redistribute it and/or modify it under the
// terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version.
// 
// Strata is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
// details.
// 
// You should have received a copy of the GNU General Public License along with
// Strata.  If not, see <http://www.gnu.org/licenses/>.
// 
// Copyright 2007 Albert Kottke
//
////////////////////////////////////////////////////////////////////////////////

#ifndef SITE_RESPONSE_MODEL_H_
#define SITE_RESPONSE_MODEL_H_

#include "SiteProfile.h"
#include "EquivLinearCalc.h"
#include "RecordedMotion.h"
#include "RvtMotion.h"
#include "NonLinearPropertyLibrary.h"
#include "Units.h"
#include "TextLog.h"

#include <QObject>
#include <QMap>
#include <QVariant>
#include <QString>
#include <QList>
#include <QProgressBar>

class SiteResponseOutput; // Forward declaration of SiteResponseOutput

class SiteResponseModel : public QObject
{
	Q_OBJECT

	public:
		SiteResponseModel( QObject * parent = 0);
        ~SiteResponseModel();

        //! Method used to compute the site response
		enum Method { 
            RecordedMotions,  //!< Recorded motions
            RandomVibrationTheory //!< Random Vibration Theory
        };

        static QStringList methodList();

        //! Reset the object to the default values
        void reset();
        
        //! The fileName that the model was saved too or loaded from
        QString fileName() const;
		
		QString title() const;
		void setTitle(const QString & title);

		QString notes() const;
		void setNotes(const QString & notes);

		QString filePrefix() const;
		void setFilePrefix(const QString & prefix);

        QString lengthUnits() const;
        QString volUnits() const;
        QString massUnits() const;

		Method method() const;
		void setMethod(Method method);

        bool saveMotionData() const;
        void setSaveMotionData(bool saveData);
        
        bool okToContinue() const;
        //! Set that it is okay to continue computing
        void setOkToContinue(bool okToContinue);

        Units * units();

        TextLog & textLog();
		SiteProfile & siteProfile();
		EquivLinearCalc & calculator();
        QList<RecordedMotion*> & recordedMotions();
        RvtMotion * rvtMotion();

        NonLinearPropertyLibrary * nlPropertyLibrary();

        SiteResponseOutput * output();

        //! Load the model from a file
        bool load(const QString & fileName);

        //! Save the model to a file
        bool save(const QString & fileName);

        //! Compute the site response
        void compute( QProgressBar * progressBar = 0);

		QMap<QString, QVariant> toMap() const;
		void fromMap(const QMap<QString, QVariant> & map);

        //! Create a html document containing the information of the model
        QString toHtml();

    signals:
        void recordedMotionsChanged();
        void rvtMotionChanged();
	
	private:
        //! Name of the file
        QString m_fileName;

        //! Title of the project
		QString m_title;

        //! Notes on the project for sanity of the user
		QString m_notes;
        
        //! The prefix of filenames generated by the program
		QString m_filePrefix;

        //! Units of the analysis
		Units * m_units;
        
        //! Type of analysis
		Method m_method;
        
        //! Contains all information about the site
		SiteProfile m_siteProfile;
        
        //! The object responsible for computing the site response
		EquivLinearCalc m_calculator;

        //! Okay to continue calculation
        bool m_okToContinue;
        
        //! A list of recorded motions
        /*! Both the recorded and random vibration theory motions are stored in
         * the SiteResponseModel as it allows the same site to be easily
         * analysis using the two different methods.
         */
        QList<RecordedMotion*> m_recordedMotions;
        
        //! Save the motion data in the input file
        bool m_saveMotionData;
        
        //! The motion used for the random vibration theory analysis
        RvtMotion * m_rvtMotion;

        //! Ouput from the analysis
        SiteResponseOutput * m_output;

        //! Previously defined non-linear curves
        NonLinearPropertyLibrary * m_nlPropertyLibrary;

        //! Log for the output
        TextLog m_textLog;
};
#endif
