name: build-linux

on: [push, pull_request]


jobs:
  build:
    # Based on requirement by linuxdeployqt
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo add-apt-repository ppa:beineri/opt-qt-5.15.2-bionic
          sudo apt-get update
          sudo apt-get install -y cmake libgsl-dev libgl1-mesa-dev qt515base qt515tools qt515svg
      - name: build qwt
        shell: bash
        run: |
          git clone --branch qwt-6.2 https://git.code.sf.net/p/qwt/git qwt
          cd qwt
          source /opt/qt515/bin/qt515-env.sh
          qmake --version
          qmake
          make -j2
      - name: build strata
        run: |
          source /opt/qt515/bin/qt515-env.sh
          mkdir build
          cd build
          LD_LIBRARY_PATH=$(readlink -f ../qwt/lib):$LD_LIBRARY_PATH
          cmake .. -DQWT_ROOT_DIR=../qwt -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:STRING=dist
          cmake --build . --target install
          ./dist/usr/bin/strata -v
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: strata
          path: ${{github.workspace}}/build/dist/usr/bin/strata
          retention-days: 5
  find-tests:
    runs-on: ubuntu-18.04
    outputs:
      tests: ${{ steps.find-tests.outputs.tests }}
    steps:
      - uses: actions/checkout@v2
      - name: find tests
        working-directory: ${{github.workspace}}/example
        run: |
          tests=$(ls *.json *.strata | jq -cnR '[inputs | select(length>0)]')
          echo $tests
          echo "::set-output name=tests::$tests"
  test:
    runs-on: ubuntu-18.04
    needs: [find-tests, build]
    strategy:
      fail-fast: false
      matrix:
        case: ${{ fromJson(needs.find-tests.outputs.tests) }}
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qt5-default gsl-bin libqwt-qt5-6
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: strata
          path: ${{github.workspace}}
      - name: perform tests
        run: |
          # Permissions reset on downloading artifact
          chmod +x strata
          ./strata -b example/${{ matrix.case }}
  create-appimage:
    runs-on: ubuntu-18.04
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qt5-default gsl-bin libqwt-qt5-6
      - name: create appimage
        run: |
          # Create the AppImage
          wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
          chmod a+x linuxdeployqt-continuous-x86_64.AppImage
          ARCH=x86_64 ./linuxdeployqt-continuous-x86_64.AppImage dist/strata.desktop -appimage -no-translations
          # Rename and upload the AppImage
          VERSION=$(sed -ne 's/.*VERSION "\([0-9.]\+\)".*/\1/p' ../CMakeLists.txt)
          GITHASH=$(git rev-parse --short HEAD)
          IMAGE=Strata-v$VERSION-$GITHASH-x86_64.AppImage
          mv Strata-*.AppImage $IMAGE
      - uses: actions/upload-artifact@v3
        with:
          name: strata appimage
          path: ${{ github.workspace }}/Strata-*.AppImage
