name: build-windows

on: [push, release]


jobs:
  build:
    # Based on requirement by linuxdeployqt
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
      - name: install qwt
        shell: bash
        working-directory: ${{github.workspace}}/..
        run: |
          git clone --branch qwt-6.2 https://git.code.sf.net/p/qwt/git qwt
          cd qwt
          qmake
          nmake
      - name: install gsl
        shell: bash
        working-directory: ${{github.workspace}}/..
        run: |
          git clone https://github.com/ampl/gsl.git gsl
          cd gsl
          git submodule update --init --recursive
          cmake ^
           -DGSL_DISABLE_WARNINGS:BOOL=ON^
           -DBUILD_SHARED_LIBS:BOOL=ON^
           -DMSVC_RUNTIME_DYNAMIC:BOOL=ON^
           -DCMAKE_BUILD_TYPE="Release"^
           -G "%CMAKE_GENERATOR%"^
           .
          cmake --build . --target install
      - name: build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:STRING=dist
          cmake --build . --target install
          ./dist/usr/bin/strata -v
