name: build-windows

on: [push, release]


jobs:
  build:
    # Based on requirement by linuxdeployqt
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          extra:   --external 7z
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: actions/cache@v3
        id: cache
        with:
          path: ${{ github.workspace }}/deps
          key: ${{ runner.os }}
      - name: Build dependencies (qwt & gsl)
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir deps
          cd deps
          git clone --branch qwt-6.2 https://git.code.sf.net/p/qwt/git qwt
          cd qwt
          qmake
          nmake
          cd ..
          git clone https://github.com/ampl/gsl.git gsl
          cd gsl
          git submodule update --init --recursive
          cmake -DGSL_DISABLE_WARNINGS:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON -DMSVC_RUNTIME_DYNAMIC:BOOL=ON -DCMAKE_BUILD_TYPE="Release" -DGSL_DISABLE_TESTS=1 -DNO_AMPL_BINDINGS=1 -DDOCUMENTATION=OFF -G "Visual Studio 16 2019" .
          cmake --build . --target install
      - name: build
        run: |
          mkdir build
          cd build
          cmake .. -DQWT_ROOT_DIR="../deps/qwt" -DQWT_ROOT_DIR="../deps/gsl" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:STRING=dist
          cmake --build . --target install
          dist/usr/bin/strata.exe -v
